// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCp5CghBdXRoVHlwZRISCg5BVVRIX1RZ",
            "UEVfTk9ORRAAEhYKEkFVVEhfVFlQRV9XT09OR0xFRRABEhQKEEFVVEhfVFlQ",
            "RV9HT09HTEUQAhIWChJBVVRIX1RZUEVfRkFDRUJPT0sQAxITCg9BVVRIX1RZ",
            "UEVfQVBQTEUQBCpoCgpQbGF5ZXJUeXBlEhQKEFBMQVlFUl9UWVBFX05PTkUQ",
            "ABIWChJQTEFZRVJfVFlQRV9LTklHSFQQARIUChBQTEFZRVJfVFlQRV9NQUdF",
            "EAISFgoSUExBWUVSX1RZUEVfQVJDSEVSEAMqOgoNQ3JlYXR1cmVTdGF0ZRII",
            "CgRJZGxlEAASCgoGTW92aW5nEAESCQoFU2tpbGwQAhIICgREZWFkEAMqMAoH",
            "TW92ZURpchIGCgJVcBAAEggKBERvd24QARIICgRMZWZ0EAISCQoFUmlnaHQQ",
            "AypDCg5HYW1lT2JqZWN0VHlwZRIICgROb25lEAASCgoGUGxheWVyEAESCwoH",
            "TW9uc3RlchACEg4KClByb2plY3RpbGUQA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.AuthType), typeof(global::Protocol.PlayerType), typeof(global::Protocol.CreatureState), typeof(global::Protocol.MoveDir), typeof(global::Protocol.GameObjectType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum AuthType {
    [pbr::OriginalName("AUTH_TYPE_NONE")] None = 0,
    [pbr::OriginalName("AUTH_TYPE_WOONGLEE")] Woonglee = 1,
    [pbr::OriginalName("AUTH_TYPE_GOOGLE")] Google = 2,
    [pbr::OriginalName("AUTH_TYPE_FACEBOOK")] Facebook = 3,
    [pbr::OriginalName("AUTH_TYPE_APPLE")] Apple = 4,
  }

  public enum PlayerType {
    [pbr::OriginalName("PLAYER_TYPE_NONE")] None = 0,
    [pbr::OriginalName("PLAYER_TYPE_KNIGHT")] Knight = 1,
    [pbr::OriginalName("PLAYER_TYPE_MAGE")] Mage = 2,
    [pbr::OriginalName("PLAYER_TYPE_ARCHER")] Archer = 3,
  }

  public enum CreatureState {
    [pbr::OriginalName("Idle")] Idle = 0,
    [pbr::OriginalName("Moving")] Moving = 1,
    [pbr::OriginalName("Skill")] Skill = 2,
    [pbr::OriginalName("Dead")] Dead = 3,
  }

  public enum MoveDir {
    [pbr::OriginalName("Up")] Up = 0,
    [pbr::OriginalName("Down")] Down = 1,
    [pbr::OriginalName("Left")] Left = 2,
    [pbr::OriginalName("Right")] Right = 3,
  }

  public enum GameObjectType {
    [pbr::OriginalName("None")] None = 0,
    [pbr::OriginalName("Player")] Player = 1,
    [pbr::OriginalName("Monster")] Monster = 2,
    [pbr::OriginalName("Projectile")] Projectile = 3,
  }

  #endregion

}

#endregion Designer generated code
